apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: stream-scaling-policy
spec:
  targetRef:
    apiVersion: "batch/v1"
    kind:       Job
    name:       stream-1
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 1
          memory: 4000Mi
        maxAllowed:
          cpu: 1
          memory: 4000Mi
        controlledResources: ["cpu", "memory"]

