apiVersion: batch/v1
kind: Job
metadata:
  name: sgt
spec:
  manualSelector: true
  selector:
    matchLabels:
      app: sgt
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: sgt
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
      - name: sgt
        image: raijenki/mpik8s:sigwatcher
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /data
            name: task-pv-storage
        command: ["/home/a.out"]
        resources:
          requests:
            cpu: 1
            memory: "1500Mi"
          limits:
            cpu: 1
            memory: "1500Mi"
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
