apiVersion: v1
kind: Pod
metadata:
  name: autodock-gpu
spec:
  restartPolicy: OnFailure
  runtimeClassName: nvidia
  containers:
    - name: autodock-gpu
      image: "raijenki/autodock:1.5.3-gpu2"
      command:
        - "/bin/sh" 
        - "-c"
        - "/home/AutoDock-GPU/bin/./autodock_gpu_64wi --ffile /home/AutoDock-GPU/input/1stp/derived/1stp_protein.maps.fld --lfile /home/AutoDock-GPU/input/1stp/derived/1stp_ligand.pdbqt"
      resources:
        limits:
          nvidia.com/gpu: 1
      env:
      - name: NVIDIA_VISIBLE_DEVICES
        value: all
      - name: NVIDIA_DRIVER_CAPABALITIES
        value: compute,utility
