apiVersion: batch/v1
kind: Job
metadata:
  name: dgemm
spec:
  manualSelector: true
  selector:
    matchLabels:
      app: dgemm
  backoffLimit: 1
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: dgemm
    spec:
      containers:
      - name: dgemm
        image: raijenki/mpik8s:dgemm
        imagePullPolicy: IfNotPresent
        command: ["/home/mt-dgemm"]
        args: ["2000", "500"]
        resources:
          requests:
            cpu: 1
            memory: "4096Mi"
          limits:
            cpu: 1
            memory: "4096Mi"
        env:
          - name: OMP_NUM_THREADS
            valueFrom:
              resourceFieldRef:
                containerName: dgemm
                resource: requests.cpu
      restartPolicy: OnFailure
