apiVersion: v1
kind: Pod
metadata:
  name: dgemm-1
spec:
  containers:
  - name: dgemm-1
    image: raijenki/mpik8s:dgemm
    command:
      - /bin/sh
      - -c
      - |
        ./home/mt-dgemm
    resources:
      requests:
        cpu: "1000m"
        memory: "512Mi"
