apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgemm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dgemm
  template:
    metadata:
      labels:
        app: dgemm
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
      - name: dgemm
        image: raijenki/mpik8s:dgemm
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /data
            name: task-pv-storage
        command:
          - /bin/sh
          - -c
          - | 
            ./home/mt-dgemm 10000 50000
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
