apiVersion: batch/v1
kind: Job
metadata:
  name: stream-1
spec:
  manualSelector: true
  selector:
    matchLabels:
      app: stream-1
  backoffLimit: 1
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: stream-1
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
      - name: stream-1
        image: raijenki/mpik8s:stream
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /data
            name: task-pv-storage
        env:
          - name: OMP_NUM_THREADS
            value: "8"
        command: ["/home/stream_c"]
        args: ["50"]
        resources:
          requests:
            cpu: 1
            memory: "4000Mi"
          limits:
            cpu: 1
            memory: "4000Mi"
      restartPolicy: OnFailure
