apiVersion: batch/v1
kind: Job
metadata:
  name: stream-1
spec:
  backoffLimit: 1
  template:
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
      - name: stream-1
        image: raijenki/mpik8s:stream
        volumeMounts:
          - mountPath: /data
            name: task-pv-storage
        command:
          - /bin/sh
          - -c
          - | 
            ./home/stream_c
        resources:
          requests:
            cpu: "2000m"
            memory: "2048Mi"
          limits:
            cpu: "4000m"
            memory: "4096Mi"
      restartPolicy: Never
