apiVersion: batch/v1
kind: Job
metadata:
  name: stream-1
spec:
  manualSelector: true
  selector:
    matchLabels:
      app: stream-1
  backoffLimit: 10
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: stream-1
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
      - name: stream-1
        image: raijenki/mpik8s:stream
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /data
            name: task-pv-storage
        command:
          - /bin/bash
          - -c
          - |
            time /home/stream_c 2000
        resources:
          requests:
            cpu: 2
            memory: "4000Mi"
          limits:
            cpu: 2
            memory: "4000Mi"
        env:
          - name: OMP_NUM_THREADS
            valueFrom:
              resourceFieldRef:
                containerName: stream-1
                resource: requests.cpu
      restartPolicy: OnFailure
