apiVersion: batch/v1
kind: Job
metadata:
  name: stream-1
spec:
  manualSelector: true
  selector:
    matchLabels:
      app: stream-1
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: stream-1
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
      - name: stream-1
        image: raijenki/mpik8s:stream
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: /data
            name: task-pv-storage
        command:
          - /bin/sh
          - -c
          - | 
            OMP_NUM_THREADS=2 ./home/stream_c
        resources:
          requests:
            cpu: "2000m"
            memory: "1500Mi"
          limits:
            cpu: "2000m"
            memory: "1500Mi"
      restartPolicy: OnFailure
